### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by johansmitsnl** [opal/opal-jquery#100]
When can a new release take place?

Hyperloop/Hyperstack is working on releasing the gems but we need the master build. Would be fantastic if a new release could take place and we can drop the github rule from our gems.

**Comment by elia** [comment]
Sorry for the long delay, a new version has been released [in September](https://github.com/opal/opal-jquery/blob/a00b5546520e3872470962c7392eb1a1a4236112/CHANGELOG.md#043-2018-09-07): https://rubygems.org/gems/opal-jquery/versions/0.4.3
