### ISSUE TITLE
ajaxComplete

### ISSUE THREAD

**Issue by epipheus** [opal/opal-jquery#102]
I hate clouding issues with questions but I don't see an answer for this anywhere.  How would I access the equivalent of `$(document).ajaxComplete(`

**Comment by enatividad** [comment]
try doing this:

```ruby
# main.rb
`$(document).ajaxComplete(function() { /* js code here */ })`
```
if you need to use ruby variables, I think you have to interpolate.

**Comment by elia** [comment]
See also https://github.com/opal/opal/issues/1994#issuecomment-510248828
