### ISSUE TITLE
$$ is not a function

### ISSUE THREAD

**Issue by jasonl99** [opal/opal-jquery#107]
```javascript
/* Generated by Opal 1.0.0 */
Opal.modules["opal/jquery"] = function(Opal) {
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$;

  Opal.add_stubs(['$==', '$require']);
  if ($$($nesting, 'RUBY_ENGINE')['$==']("opal")) {
    
    self.$require("opal/jquery/window");
    self.$require("opal/jquery/document");
    self.$require("opal/jquery/element");
    self.$require("opal/jquery/event");
    self.$require("opal/jquery/http");
    return self.$require("opal/jquery/kernel");
  } else {
    return nil
  }
};
```

I can't for the life of me figure this out.  The `if ($$($nesting, 'RUBY_ENGINE')...` is where it's failing.   

<img width="483" alt="image" src="https://user-images.githubusercontent.com/1554969/75359233-1d5f5080-5882-11ea-89f8-1cf90a3ee2bc.png">

I have a very basic shell of a Roda app that I'm playing around with to evaluate opal.

**Comment by jasonl99** [comment]
I figured this one out - it was using Opal 1.0.0.  Switching to 1.0.3 fixed the issue.

**Comment by elia** [comment]
@jasonl99 can it be that you had some older compiled version of opal.js? 
Anyway if it's solved we can probably close this issue 👍

**Comment by jasonl99** [comment]
I tried earlier, github wouldn't let me close it.  Yes, I had an older compiled version from a straight `gem install` and hadn't run `bundle exec...` ...definitely my fault, but that was an interesting one to figure out.
