### ISSUE TITLE
on mobile can't get more than first touch 

### ISSUE THREAD

**Issue by jeezs** [opal/opal-jquery#109]
in order to capture more than the first touch, the 'touch def' should accept optional params : 

 def touch_x(touch_nb = 0)
    `#@native.originalEvent.touches[#{touch_nb}].pageX`
  end

  def touch_y(touch_nb = 0)
    `#@native.originalEvent.touches[#{touch_nb}].pageY`
  end

**Comment by elia** [comment]
@jeezs the proposed implementation looks good, can you please submit a pull-request with that change?
