### ISSUE TITLE
Event#touch_x raises a TypeError that can't be rescued

### ISSUE THREAD

**Issue by dan42** [opal/opal-jquery#116]
On `touchend` events, the originalEvent has neither pageX/Y nor touches.
```
begin
  $$.alert(event.touch_x)
rescue 
  $$.alert('error')
end
```
The code above crashes with `Uncaught TypeError: Cannot read properties of undefined (reading '0')`
Since TypeError is a subclass of StandardError, I would expect the rescue above to work, but it doesn't.
Note that `rescue Exception` does work.

I think the `#touch_x` method could be changed to
```
def touch_x
  `#@native.originalEvent.touches[0] && #@native.originalEvent.touches[0].pageX`
end
```
or
```
def touch_x
  `#@native.originalEvent.touches[0].pageX`
rescue Exception
  nil
end
```
Same applies to touch_y, obviously.

**Comment by hmdne** [comment]
We are talking about JavaScript TypeError, which is different from Ruby TypeError (they aren't bridged, they are separate classes).

The class hierarchies are somewhat like:
JS::Error (Ruby type) -> TypeError (JS)
Exception (R) -> StandardError (R) -> TypeError (R)
