### ISSUE TITLE
HTTP Get by default setting content-type application/json

### ISSUE THREAD

**Issue by jiggneshhgohel** [opal/opal-jquery#122]
When a method in my opal file runs following

```
HTTP.get(request_url) do |response|
   # handler response
end
```

then in the Request Header, in browser's Web Developer Tools, I see following content-type set

```
 Content-Type: application/json
```

That was strange because I manually didn't setup any content-type for my request and because of this unwanted content-type the request to my webapp was returning 415 "Unsupported Media Type" response instead of expected JS response having content-type set to `application/javascript`.

Checking the docs at https://api.jquery.com/jQuery.ajax/#jQuery-ajax-url-settings found following

>contentType (default: 'application/x-www-form-urlencoded; charset=UTF-8')

So how come content-type was getting set. So I checked the source code and found that it is being set by following line:

https://github.com/opal/opal-jquery/blob/v0.5.1/lib/opal/jquery/http.rb#L174

But that was strange because that line is part of following check `else if (payload != nil) {` and payload is set by following line

https://github.com/opal/opal-jquery/blob/v0.5.1/lib/opal/jquery/http.rb#L161

But as can be seen in my usage of `HTTP.get(request_url)` I didn't passed any options so passing of a `payload` option is out of question. So I added `console.log` statement in generated opal bundle JS file and I found that the local var `payload` in following line  was found set to `null`

https://github.com/opal/opal-jquery/blob/v0.5.1/lib/opal/jquery/http.rb#L166

and the JS code at following line

https://github.com/opal/opal-jquery/blob/v0.5.1/lib/opal/jquery/http.rb#L172

compares `payload` with `nil`. So this was the problem. In the opal bundle I modified 

```
else if (payload != nil) {
```

to

```
else if (payload != null) {
```

and the content-type didn't passed and my webapp request also succeeded.

Also along with `contentType` getting set the `data` also gets set causing my GET URLs to look like following 

```
http://localhost:2300/users/1?null=
```

Please note `null=` in the query string.

Thanks.

**Comment by AndyObtiva** [comment]
I implemented the suggested fix here:

https://github.com/opal/opal-jquery/commit/71c995ca0b90f64dabd1e4eb0c6567401fc9159c

I released it under version 0.5.2:

https://rubygems.org/gems/opal-jquery/versions/0.5.2
https://github.com/opal/opal-jquery/tree/v0.5.2

I am closing this issue as a result.

If I did not fully address your issues/concerns, please feel free to respond to this ticket even if closed (and the issue can be re-opened if needed).
