### ISSUE TITLE
Exposing plugins with #expose should handle native object conversions

### ISSUE THREAD

**Issue by adambeynon** [opal/opal-jquery#36]
`Element.expose(:my_plugin)` should create an instance method which converts ruby objects into javascript equivalents using `#to_n`. It should also implicitly convert `null` or `undefined` back into `nil`. The current behaviour just passes arguments directly.

**Comment by elia** [comment]
since if/unless now (0.10+) support `null/undefined` as falsy values and we can deal with native objects via the `JS` syntax I'll close this.
