### ISSUE TITLE
Enforce Element::find and Element::parse behaviour

### ISSUE THREAD

**Issue by lloeki** [opal/opal-jquery#45]
Currently those two are equivalent:

```ruby
Element.parse('<span />')
Element.find('<span />')
```

Conversely, those two equally work:

```ruby
Element.find('#my_id')
Element.parse('#my_id')
```

I propose to enforce the behaviour elicited by the method names, that is case 1 line 2 and case 2 line 2 should `fail ArgumentError`. AFAICT testing the first character being or not being  `<` is sufficient.

It is then arguable that `Element::[]` should stay an alias to `Element::find` or continue to mimic the kitchensink that is `$()`.

Also, while rare since we should only get toll-free jQuery-boxed elements most of the time, there is a third case of usage of the `$()` function, it's to jQuery-box unboxed DOM element instances. To that end `Element::find` and `Element::[]` are equivalent, which feels weird. Maybe adding an `Element#box` method is in order?

**Comment by elia** [comment]
This should solve `::parse` http://api.jquery.com/jQuery.parseHTML/. `::find` is already linked to `$.find`

http://api.jquery.com/jQuery.parseHTML/
