### ISSUE TITLE
It would be great if certains kinds of gems were available using Opal Jquery

### ISSUE THREAD

**Issue by akshatpradhan** [opal/opal-jquery#63]
One of the nice things about Rails is that there are gems available to handle a lot of UI cases (e.g. wicked wizard) and even reactive cases (e.g. best_in_place). It would be great if those kinds of gems were available using Opal to handle other interaction cases.

**Comment by elia** [comment]
Completely agree. 

Alas, it's not something we can do much about but trying to make the community & ecosystem thrive.
Anyway there's a [README section dedicated to the usage of jQuery plugins](https://github.com/opal/opal-jquery/blob/f70f8e3ba95e06f961299c288c6196424287dd73/README.md#usage-of-jquery-plugins) and there is [a respectable number of opal-related gems being published on rubygems](https://rubygems.org/search?utf8=✓&query=opal),* last but not least wrt react stuff don't miss [react.rb](https://github.com/zetachang)

_* the list is not complete, but you get the idea_

_sorry for the delay! 😖_
