### ISSUE TITLE
using the xhr option in an HTTP.put

### ISSUE THREAD

**Issue by catmando** [opal/opal-jquery#66]
Not at all sure how to do this...
I am trying to add an XHR call back to an "Opal-JQuery" HTTP.put method call.

Its not clear what goes in the XHR option.  In jQuery its a function that will create and return the XHR object.

Not clear what to do when doing this with opal.  

For example `HTTP.put("my.big.url", xhr: what_goes_here)`

I have tried various options and looked through the code... I can't figure it out.

**Comment by catmando** [comment]
Figured it out:

xhr: works with lambda only.

lambdas have to_n implemented, but methods do not, so doing an xhr: lambda { ... } works but xhr: method(:foo) does not.

will update docs and do a pull request

**Comment by elia** [comment]
great :)

**Comment by elia** [comment]
I think this is closed by dc644be0a9d0f32f5eba8a3493185a0a4c9be49a :wink:
