### ISSUE TITLE
prepend method missing in element.rb

### ISSUE THREAD

**Issue by hayley** [opal/opal-jquery#67]
I noticed that the `prepend` method existed in an older version of the library:
https://github.com/opal/opal-jquery/blob/v0.2.0/opal/opal-jquery/element.rb

But no longer exists in the current element.rb code:
https://github.com/opal/opal-jquery/blob/master/lib/opal/jquery/element.rb

**Comment by the-robear** [comment]
I'd like to second this!

**Comment by adambeynon** [comment]
Added via ee3364c. Might be a couple of days before release though, so you will need to use git/master version.

**Comment by the-robear** [comment]
Cool thanks!

**Comment by elia** [comment]
Released in v0.4
