### ISSUE TITLE
Using element.on(:click) {<code>} seems to accumulate "on(:click)" events?

### ISSUE THREAD

**Issue by simonsen78** [opal/opal-jquery#74]
Hi

I am using this code:

    def select_page id
      puts "Selected Page: #{id}"
      @page_edit_btn.remove_class "disabled"
      @page_edit_btn.on(:click) { edit_page( id ) }
    end

    def edit_page id
      puts "Editing page: #{id}!"      
    end

This code is (in my mind) supposed to _set_ only one "on click" attribute to the edit button. The user selects a page item and can then edit it by pressing the "Edit" button. But it seems to _add_ one instead, everytime this script is run.

If I click on five different page items in the list and click the 'edit' button, then I will get 5 lines of log output; "Editing page <x>" from the "edit_page" method.

Is this the expected behavior, or am I supposed to nil on(:click) somehow each time?

Thanks!

**Comment by elia** [comment]
how many times is `"Selected Page: #{id}"` printed in the console?

**Comment by simonsen78** [comment]
Once for every time I click a Page item in the list:

LOG:
------------------------------
Selected Page: 88
Selected Page: 4
Selected Page: 2
< here I click the button >
Editing page: 88!
Editing page: 4!
Editing page: 2!

**Comment by elia** [comment]
ok, try checking the size of `@page_edit_btn` with something like:

```rb
puts @page_edit_btn.size
```

if it's more than one, you may need to adjust your selector

**Comment by simonsen78** [comment]
I put the code at the end of the "select_page" method:

  puts "Page edit button size: #{@page_edit_btn.size}"

LOG:
Selected Page: 88
Page edit button size: 1
Selected Page: 4
Page edit button size: 1
Selected Page: 6
Page edit button size: 1
Selected Page: 7
Page edit button size: 1
  < button pressed here >
Editing page: 88!
Editing page: 4!
Editing page: 6!
Editing page: 7!

**Comment by elia** [comment]
you mean there's only one button in the html?

maybe would be good to post the HTML as well

**Comment by simonsen78** [comment]
Not actually a button, but an 'a' element, styled as a button using the Materialize framework.

From the body:

    ...
    <div class="col s11 m11 l11">
      <div class="section">
      <script src="/js/build.js"></script>
      <div class="row">
        <div class="col l3">
          <h4 class="thin" id="pageheader">Pages</h4>
          <a class="btn-flat waves-effect waves-green" id="page-new-btn">New</a>
          <a class="btn-flat waves-effect waves-blue disabled" id="page-edit-btn">Edit</a>
          <a class="btn-flat waves-effect waves-red disabled" id="page-delete-btn">Delete</a>
          <div class="pagewindow" id="pagelist" style="height:80%"></div>
      </div>
    ...

So just one "button" used to edit the selcted Page item.

**Comment by simonsen78** [comment]
I can also click the same item X amount times, which results in X lines of "Editing Page: <id>" in the log.

**Comment by elia** [comment]
I assume the "button" is this: `<a class="btn-flat waves-effect waves-blue disabled" id="page-edit-btn">Edit</a>`. If that's the case it's just how jQuery works, it will append an event each time you call `.on` on the event, it won't replace the old event.

A solution could be to keep track of the previous event and offload it before setting the new event.

Something like this should work:

```ruby
  puts "Selected Page: #{id}"
  @page_edit_btn.off @current_event if @current_event
  @page_edit_btn.remove_class "disabled"
  @current_event = @page_edit_btn.on(:click) { edit_page( id ) }
```

**Comment by simonsen78** [comment]
@page_edit_btn.off(:click)

This did the trick, thanks! Guess I need to brush up on my JQuery :-)
