### ISSUE TITLE
jQuery is accessed via $ instead of jQuery

### ISSUE THREAD

**Issue by Quincunx271** [opal/opal-jquery#75]
jQuery is not the only javascript library to use the `$` variable. However, when I looked at the source of opal-jquery, it appears that it accesses jQuery via the `$` variable. This will cause problems if someone used [`jQuery.noConflict()`](https://api.jquery.com/jQuery.noConflict/) or anything of the like. Changing all the `$`s to `jQuery`s would fix this.

**Comment by elia** [comment]
Yes that used to be the case I think, but currently the `$` var you see around the code comes from a closure variable that is local to the class definition and it's defined like this:

```rb
`var $ = #{JQUERY_SELECTOR.to_n}`
```

(eg. [here](https://github.com/opal/opal-jquery/blob/master/lib/opal/jquery/element.rb#L53))

`JQUERY_SELECTOR` comes from `window.jQuery` (via its Opal `Native` equivalent: `$$[:jQuery]`)

https://github.com/opal/opal-jquery/blob/master/lib/opal/jquery/constants.rb
