### ISSUE TITLE
Missing native wrapping of Element#prop yields to JS errors

### ISSUE THREAD

**Issue by Papierkorb** [opal/opal-jquery#78]
Hi,

Over at https://github.com/opal/opal/issues/1049 I found that by trying to test for the existence for a specific DOM property, that Element#prop at least, and probably others too, don't wrap `undefined`. This leads to issues in the generated JavaScript, as Opal does not expect `undefined` to appear as variable value.

In my app, I use the following work-around. If it's helpful, feel free to make use of it:

``` ruby
class Element
  def property(name, toggle = nil)
    return prop(name, toggle) unless toggle.nil?

    `(self.prop(#{name}) === true || self.prop(#{name}) === "true")`
  end
end
```

**Comment by elia** [comment]
fixed by the fact that null/undefined are now (0.10+) considered falsy values
