### ISSUE TITLE
HTTP.get doesn't serialize get data (#{payload}) to query string.

### ISSUE THREAD

**Issue by classyPimp** [opal/opal-jquery#79]
I may be wrong but it probably should serialize it to query string properly, but now it simply appends it like a string.
e.g. payload: {foo: "bar"} will result in {foo:bar} string appended, instead of ?foo=bar
Maybe this should go in HTTP:

```
%x{
      if (#{@method == "get"}) {
        payload = #{@payload.to_n};
        #{settings}.data = $.param(payload);
      }
```

And passing payload: {foo: "bar"} will behave as expected for HTTP.get.

**Comment by elia** [comment]
@classyPimp seems this right fix, can you send a PR for it? 

(Attaching tests would be great too, of course :smiley:)

**Comment by classyPimp** [comment]
I would gladly do, but I can't provide a test because: I can't access the request headers query strings. (response url would return it without query string).
`
%x{
     if (typeof(#{payload}) === 'string') {
        #{settings}.data = payload;
      }
#This would properly serialize:
      if (#{@method == "get" && payload.is_a?(Hash)}) {
        settings.data = #{payload.to_n}
      }
      else if (payload != nil) {
        settings.data = payload.$to_json();
        settings.contentType = 'application/json';
      }
}
`

**Comment by daltonrenaldo** [comment]
any update on this? I'm having the same issue

**Comment by classyPimp** [comment]
I've just monkey-patch it in my apps. Add this in your code.
```
class HTTP
  def send(method, url, options, block)
    @method   = method
    @url      = url
    @payload  = options.delete :payload
    @handler  = block

    @settings.update options

    settings, payload = @settings.to_n, @payload

    %x{
      if (#{@method == "get" && @payload != nil}) { #<====this is added
        payload = #{@payload.to_n};
        #{settings}.data = $.param(payload);
      }
      else if (typeof(#{payload}) === 'string') {
        #{settings}.data = payload;
      }
      else if (payload != nil) {
        settings.data = payload.$to_json();
        settings.contentType = 'application/json';
      }
      settings.url  = #@url;
      settings.type = #{@method.upcase};
      settings.success = function(data, status, xhr) {
        return #{ succeed `data`, `status`, `xhr` };
      };
      settings.error = function(xhr, status, error) {
        return #{ fail `xhr`, `status`, `error` };
      };
      $.ajax(settings);
    }

    @handler ? self : promise
  end
end
```

**Comment by elia** [comment]
This can be achieved by passing `data: {foo: :bar}` instead of `payload: {foo: :bar}`, the contents of data will be prepared via `#to_n`
