### ISSUE TITLE
HTTP.post with hash payload results in an OPTIONS request

### ISSUE THREAD

**Issue by essenciary** [opal/opal-jquery#81]
The following code 
```opal> HTTP.post('http://example.com', payload: {a: 'b'})```
``` => #<Promise(855)> ```

generates the following OPTIONS request (in Chrome, Mac OS X), with the payload data getting lost: 
```Remote Address:93.184.216.34:80```
```Request URL:http://example.com/```
```Request Method:OPTIONS```
```Status Code:200 OK```

======

A string payload will work as expected, but that's not the ruby way: 
```opal> HTTP.post('http://example.com', payload: 'a=b&c=d')```
``` => #<Promise(967)> ```

Results in 
```Remote Address:93.184.216.34:80```
```Request URL:http://example.com/```
```Request Method:POST```
```Status Code:200 OK```

with the payload being correctly POSTed.

**Comment by meh** [comment]
You're likely getting in CORS-land, and you should never go alone.

An `OPTIONS` request is sent to the server to check the request is appropriate, it happens when the request has certain things, I don't exactly remember which.

Basically check your server is configured properly for CORS.

**Comment by essenciary** [comment]
Roger that. Will explore and follow up. Cheers!

**Comment by essenciary** [comment]
It was indeed a CORS issue, thanks!
