### ISSUE TITLE
opal-jquery 0.4.2 does not work with Opal 0.11

### ISSUE THREAD

**Issue by bwl21** [opal/opal-jquery#98]
Trying to update to Opal 0.11 yields the following messages:

I think it can be solved by releasing another version of opal-jquery to rubygems.org.

```
bundle update opal
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "opal":
  In Gemfile:
    opal (~> 0.11.0)

    opal (~> 0.11.0) x86-mingw32

    opal-jquery x86-mingw32 was resolved to 0.4.2, which depends on
      opal (< 0.11.0, >= 0.7.0)

    opal-jquery x86-mingw32 was resolved to 0.4.2, which depends on
      opal (< 0.11.0, >= 0.7.0) x86-mingw32
```

**Comment by enatividad** [comment]
0.4.3 has been released. this can be closed mow, right?

**Comment by bwl21** [comment]
we need another update for opal 1.0 I am waiting for the same. Nor sure if we close this and create a new one. Elia has announced that the opal related gems will be updated soon.

**Comment by elia** [comment]
Yeah, I'm working on this, although slowly, the big beast is actually opal-rspec, but that prevents from running specs here

**Comment by elia** [comment]
0.4.3 supports Opal 0.11 (sorry for the late update)

**Comment by bwl21** [comment]
Does it also support Opal 1.0 - which I am using meanwhile
